apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcart-config
  namespace: cloudcart
data:
  DB_HOST: "cloudcart-mysql.cloudcart.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "cloudcart"
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "cloudcart-product-images"
