apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: cloudcart
  labels:
    app: cloudcart-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudcart-frontend
  template:
    metadata:
      labels:
        app: cloudcart-frontend
    spec:
      containers:
        - name: frontend
          image: <DOCKERHUB_USERNAME>/cloudcart-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
